name: sama_client_flutter
description: "The SAMA client for Flutter"
publish_to: 'none'
version: 0.0.1+1

environment:
  sdk: '>=3.3.0 <4.0.0'

dependencies:
  app_set_id: ^1.2.0
  bloc: ^8.1.4
  bloc_concurrency: ^0.2.5
  blurhash_dart: ^1.2.1
  cached_network_image: ^3.3.1
  collection: ^1.18.0
  connectivity_plus: ^6.0.3
  cupertino_icons: ^1.0.6
  equatable: ^2.0.5
  file_picker: ^8.0.6
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.5
  flutter_blurhash: ^0.8.2
  flutter_image_compress: ^2.3.0
  flutter_secure_storage: ^9.2.2
  flutter_staggered_grid_view: ^0.7.0
  formz: ^0.7.0
  go_router: ^14.1.4
  http: ^1.2.2
  image: ^4.2.0
  intl: ^0.19.0
  mime: ^1.0.5
  path: ^1.9.0
  path_provider: ^2.1.3
  receive_sharing_intent: ^1.8.0
  sqflite: ^2.3.3+1
  stream_transform: ^2.1.0
  url_launcher: ^6.3.0
  uuid: ^4.4.0
  video_compress: ^3.1.3
  video_thumbnail: ^0.5.3
  web_socket_channel: ^3.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/
