name: sama_client_flutter
description: "The SAMA client for Flutter"
publish_to: 'none'
version: 0.0.1+1

environment:
  sdk: '>=3.3.0 <4.0.0'

dependencies:
  app_set_id: ^1.2.0
  bloc: ^8.1.4
  bloc_concurrency: ^0.2.5
  cached_network_image: ^3.3.1
  connectivity_plus: ^6.0.3
  cupertino_icons: ^1.0.6
  equatable: ^2.0.5
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.5
  flutter_blurhash: ^0.8.2
  flutter_staggered_grid_view: ^0.7.0
  formz: ^0.7.0
  go_router: ^14.1.4
  intl: ^0.19.0
  path: ^1.9.0
  sqflite: ^2.3.3+1
  stream_transform: ^2.1.0
  uuid: ^4.4.0
  web_socket_channel: ^3.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/icons/
