import 'dart:ui';

const Color white = Color(0xFFFFFFFF);
const Color lightWhite = Color(0xFFF9F9F9);
const Color smokyWhite = Color(0xFFF6F6F6);
const Color gainsborough = Color(0xFFE7E7E7);
const Color semiBlack = Color(0x42000000);
const Color whiteAluminum = Color(0xFFB0B0B0);
const Color dullGray = Color(0xFF6D6D6D);
const Color signalBlack = Color(0xFF2A2A2A);
const Color blackBlue = Color(0xFF1B1B1D);
const Color black = Color(0xFF000000);
const Color lightMallow = Color(0xFFDBDCFC);
const Color slateBlue = Color(0xFF7678E5);
const Color cyan = Color(0xFF00FFFF);
const Color limeGreen = Color(0xFF00FF00);
const Color green = Color(0xFF4CAF50);
const Color gold = Color(0xFFFFD700);
const Color yellow = Color(0xFFFFFF00);
const Color lightPink = Color(0xFFFFB6C1);
const Color orange = Color(0xFFFFA500);
const Color redPurple = Color(0xFF68174D);
const Color red = Color(0xFFDF2E38);
