default_platform(:ios)

platform :ios do
  desc "Push a new beta build to TestFlight"
  lane :beta do
    build_app(workspace: "Runner.xcworkspace", scheme: "Runner")
    update_code_signing_settings(
      use_automatic_signing: true,
    )
    upload_to_testflight(skip_waiting_for_build_processing: true)
  end
end